global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: "mi-servicio"
    metrics_path: /latam/metrics.ashx   # aquí va el path
    static_configs:
      - targets: ["webtesting.essen.com.ar:743"]   # aquí solo host:puerto


  # - job_name: 'example_api'
  #   scheme: http
  #   static_configs:
  #     - targets: ['example_api:9091']

  #  ? TODO: add your services here
  # - job_name: 'your-job-name'
  #   scheme: https
  #   static_configs:
  #     - targets: ['URL_GOES_HERE']
  #   basic_auth:
  #     username: HTTP_AUTH_USERNAME_GOES_HERE
  #     password: HTTP_AUTH_PASSWORD_GOES_HERE
